name: Gradle check

on: [push]

jobs:
  gradle-build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Gradle dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches/modules-2
        key: ${{ runner.os }}-gradle-modules-${{ hashFiles('**/*gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-modules-

    - name: Build with Gradle
      env:
        PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
      run: |
        chmod +x ./gradlew
        ./gradlew check jTR

    - name: Projektor report URL
      uses: craigatk/projektor-action@v10
      if: failure() || success()
      with:
        print-link: true
